version: '3.0'
services:
  mysql:
    image: mysql
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1106
      MYSQL_DATABASE: spring_boot_angular_student_management_system
      MYSQL_USER: john
      MYSQL_PASSWORD: 1106
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: